language: android
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.3
    - android-26

    - sys-img-armeabi-v7a-android-22

script:
  - ./gradlew build connectedCheck

jdk:
  - oraclejdk8

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"
